# Generated by Django 5.2.7 on 2025-10-27 22:15

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to=detector.models.upload_to_image1, verbose_name='Image 1')),
                ('image2', models.ImageField(upload_to=detector.models.upload_to_image2, verbose_name='Image 2')),
                ('md5_hash1', models.CharField(max_length=32, verbose_name='Hash MD5 Image 1')),
                ('md5_hash2', models.CharField(max_length=32, verbose_name='Hash MD5 Image 2')),
                ('ssim_score', models.FloatField(blank=True, null=True, verbose_name='Score SSIM')),
                ('similarity_percentage', models.FloatField(blank=True, null=True, verbose_name='Pourcentage de similarité')),
                ('verdict', models.CharField(choices=[('IDENTICAL', 'Identiques'), ('VERY_SIMILAR', 'Très similaires'), ('SIMILAR', 'Similaires'), ('DIFFERENT', 'Différentes/Falsifiées')], max_length=20, verbose_name='Verdict')),
                ('difference_map', models.ImageField(blank=True, null=True, upload_to=detector.models.upload_to_difference_map, verbose_name='Carte des différences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('analysis_duration', models.FloatField(blank=True, null=True, verbose_name="Durée de l'analyse (s)")),
            ],
            options={
                'verbose_name': "Analyse d'image",
                'verbose_name_plural': "Analyses d'images",
                'ordering': ['-created_at'],
            },
        ),
    ]
