# Generated by Django 6.0 on 2025-12-10 16:57

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='ai_analysis_details',
            field=models.JSONField(blank=True, null=True, verbose_name="Détails de l'analyse IA"),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de confiance IA'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='ai_difference_map',
            field=models.ImageField(blank=True, null=True, upload_to=detector.models.upload_to_ai_map, verbose_name='Carte IA des manipulations'),
        ),
    ]
