# Generated by Django 6.0 on 2025-12-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('detector', '0002_imageanalysis_ai_analysis_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.batchanalysis', verbose_name="Lot d'analyse"),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='api.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favori'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='api.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
